### ISSUE TITLE
(fix ) syntax error, add PDO to connet to db, and use singleton pattern for database

### ISSUE THREAD

**Issue by ZED-Magdy** [YoussefIbraheem/Scandiweb#8]
https://github.com/YoussefIbraheem/Scandiweb/blob/bfc2e60788a2249480949b08b37edaf8f3261718/src/Database/Database.php#L19

**Comment by YoussefIbraheem** [comment]
https://github.com/YoussefIbraheem/Scandiweb/commit/0437ca375e187364584e0b51119d55cb85139562
